# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday-multipart/all/faraday-multipart.rbi
#
# faraday-multipart-1.0.4

module Faraday
end
module Faraday::Multipart
  def self.multipart_post_version; end
end
