# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/hash_diff/all/hash_diff.rbi
#
# hash_diff-1.0.0

module HashDiff
  def diff(*args); end
  def left_diff(*args); end
  def right_diff(*args); end
  def self.diff(*args); end
  def self.left_diff(*args); end
  def self.patch!; end
  def self.right_diff(*args); end
end
class HashDiff::Comparison
  def combined_keys; end
  def comparable?(key); end
  def comparison_strategy(reporter); end
  def diff; end
  def equal?(key); end
  def find_differences(&reporter); end
  def hash?(value); end
  def initialize(left, right); end
  def left; end
  def left_diff; end
  def report_difference(key, reporter); end
  def right; end
  def right_diff; end
  def value_with_default(obj, key); end
end
class HashDiff::NO_VALUE
end
