# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/multipart-post/all/multipart-post.rbi
#
# multipart-post-2.2.3

module Multipart
end
module Multipart::Post
end
module Multipart::Post::Parts
end
module Multipart::Post::Parts::Part
  def length; end
  def self.file?(value); end
  def self.new(boundary, name, value, headers = nil); end
  def to_io; end
end
class Multipart::Post::Parts::ParamPart
  def build_part(boundary, name, value, headers = nil); end
  def initialize(boundary, name, value, headers = nil); end
  def length; end
  include Multipart::Post::Parts::Part
end
class Multipart::Post::Parts::FilePart
  def build_head(boundary, name, filename, type, content_len, opts = nil); end
  def initialize(boundary, name, io, headers = nil); end
  def length; end
  include Multipart::Post::Parts::Part
end
class Multipart::Post::Parts::EpiloguePart
  def initialize(boundary); end
  include Multipart::Post::Parts::Part
end
class Multipart::Post::CompositeReadIO
  def advance_io; end
  def current_io; end
  def initialize(*ios); end
  def read(length = nil, outbuf = nil); end
  def rewind; end
end
module SecureRandom
end
module Faraday
end
module Faraday::Multipart
end
