# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/oauth2/all/oauth2.rbi
#
# oauth2-2.0.6

module OAuth2
end
module OAuth2::Version
end
class OAuth2::Error < StandardError
  def body; end
  def code; end
  def description; end
  def error_message(response_body, opts = nil); end
  def initialize(response); end
  def parse_error_description(code, description); end
  def response; end
end
class OAuth2::SnakyHash < Hashie::Mash::Rash
end
class OAuth2::Authenticator
  def apply(params); end
  def apply_basic_auth(params); end
  def apply_client_id(params); end
  def apply_params_auth(params); end
  def basic_auth_header; end
  def id; end
  def initialize(id, secret, mode); end
  def mode; end
  def secret; end
  def self.encode_basic_auth(user, password); end
end
module SecureRandom
end
module Faraday
end
module Faraday::Multipart
end
